import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'mr' | 'hi';

export const translations = {
  en: {
    // Tabs
    tabHome: 'Home',
    tabFarm: 'My Farm',
    tabScan: 'AR Scan',
    tabMarket: 'Market',
    tabProfile: 'Profile',

    // Common
    chopdaJalgaon: 'Chopda, Jalgaon',
    chopda: 'Chopda',
    jalgaon: 'Jalgaon',
    seeAll: 'See All →',
    addCrop: 'Add Crop',
    details: 'Details',
    view: 'View',
    edit: 'Edit',
    daysLeftText: 'days left',
    acre: 'Acre',

    // Dashboard (Home)
    tagline: 'Smart Farming for a Better Tomorrow',
    heroTitle: 'Smart Farming,\nBright Future !',
    heroSub: 'With modern technology: Higher yield,\nlower cost, and higher profits.',
    partlyCloudy: 'Partly Cloudy',
    rainChance: 'Rain Chance',
    humidity: 'Humidity',
    windSpeed: 'Wind Speed',
    arScanCrops: 'AR Scan\nCrops',
    irrigationGuide: 'Irrigation\nGuide',
    fertilizerRecommend: 'Fertilizer\nRecommend',
    marketPrices: 'Market\nPrices',
    todaysTasks: "Today's Farm Tasks",
    task1: 'Check soil moisture (Soybean)',
    task2: 'Irrigation (Maize)',
    task3: 'Apply fertilizer (Cotton)',
    task4: 'Inspect for pests (Onion)',
    mandiDistrictSub: '(Jalgaon Mandi)',
    myCrops: 'My Crops',
    arFarmScan: 'AR Farm Scan',
    arFarmScanDesc: 'Take a photo of your crop to detect disease, growth stage and get AI advice.',
    startScanning: 'Start Scanning →',
    govtSchemes: 'Government Schemes',
    govtSchemesSub: 'Latest subsidies and schemes for farmers',
    agriProducts: 'Agri Products',
    agriProductsSub: 'Seeds, fertilizers, equipment and more',
    farmAnalytics: 'Farm Analytics',
    farmAnalyticsSub: 'Track your farm cost, yield and profit',
    weatherAdvisory: 'Weather Advisory',
    weatherAdvisorySub: 'Get crop specific weather alerts',
    promoTitle: 'Get AI Crop Guidance in Your Language',
    promoDesc: 'Take a photo or use AR to identify crop problems and get instant solution from experts.',
    tryNow: 'Try Now →',

    // Crops & Stages
    cropSoybean: 'Soybean',
    cropMaize: 'Maize',
    cropCotton: 'Cotton',
    cropOnion: 'Onion',
    cropWheat: 'Wheat',
    cropChana: 'Chana',
    cropTur: 'Tur (Arhar)',
    stageVegetative: 'Vegetative Stage',
    stageGrowing: 'Growing Stage',
    stageLandPrep: 'Land Preparation',
    stageFlowering: 'Flowering Stage',

    // My Farm
    screenTitleFarm: 'My Farm',
    screenSubFarm: 'Manage your land, crops and activities',
    totalFarmArea: 'Total Farm Area',
    cropsCount: 'My Crops (4)',
    soilHealth: 'Soil Health',
    soilHealthSub: 'Check soil nutrients and get suggestions',
    irrigation: 'Irrigation',
    irrigationSub: 'Best time & water recommendation',
    fertilizerPlan: 'Fertilizer Plan',
    fertilizerPlanSub: 'Get customized fertilizer schedule',
    filterCrops: 'My Crops',
    filterLand: 'Farm Land',
    filterTasks: 'Tasks',
    filterExpenses: 'Expenses',
    filterAnalytics: 'Analytics',
    sowingDate: 'Sowing Date',

    // Market
    screenTitleMarket: 'Market',
    screenSubMarket: 'Check latest crop prices, trends and nearby mandis',
    getLivePrices: 'Get Live\nMarket Prices',
    getLivePricesSub: 'Compare rates, find nearby mandis\nand get the best price for your crops',
    nearbyMandisBtn: 'Nearby Mandis →',
    filterCropPrices: 'Crop Prices',
    filterNearbyMandis: 'Nearby Mandis',
    filterPriceTrends: 'Price Trends',
    filterTrade: 'Sell / Buy',
    popularCrops: 'Popular Crops',
    mandiPricesTitle: 'Mandi Prices',
    tableCrop: 'Crop',
    tableModal: 'Modal Price\n(₹ / Qtl)',
    tableMin: 'Min Price\n(₹ / Qtl)',
    tableMax: 'Max Price\n(₹ / Qtl)',
    tableChange: 'Change\n(Today)',
    tableAction: 'View',
    priceTrendTitle: 'Price Trend',
    currentPrice: 'Current Price',
    vsLastWeek: 'vs last week',
    marketNews: 'Market News',
    marketNewsSub: 'Latest updates on crop prices and market trends',
    sellToBuyers: 'Sell to Buyers',
    sellToBuyersSub: 'Connect with local buyers and traders',
    priceAlerts: 'Price Alerts',
    priceAlertsSub: 'Get notified when price reaches your target',
    exportOpps: 'Export Opportunities',
    exportOppsSub: 'Check export demand and international prices',

    // Profile / Settings
    screenTitle: 'Profile',
    screenSub: 'Manage your account and farm details',
    editProfile: 'Edit Profile',
    crops: 'Crops',
    acres: 'Acres',
    pendingTasks: 'Pending Tasks',
    farmHealth: 'Farm Health',
    farmHealthLabel: 'Farm Health',
    farmHealthVal: 'Good',
    farmMgmt: 'Farm Management',
    myFarm: 'My Farm',
    myFarmSub: 'Manage your land, crops and plots',
    myFarmRecords: 'My Farm Records',
    myFarmRecordsSub: 'View crop history, expenses and yield',
    myLocations: 'My Locations',
    myLocationsSub: 'Manage farm locations and boundaries',
    accountSettings: 'Account Settings',
    personalInfo: 'Personal Information',
    personalInfoSub: 'Manage your personal details',
    privacySecurity: 'Privacy & Security',
    privacySecuritySub: 'Change password, manage data',
    notifications: 'Notifications',
    notificationsSub: 'Manage app notifications',
    appSupport: 'App & Support',
    language: 'Language',
    languageSub: 'Select your preferred language',
    appSettings: 'App Settings',
    appSettingsSub: 'Theme, units, offline mode',
    helpSupport: 'Help & Support',
    helpSupportSub: 'FAQs, contact us',
    aboutApp: 'About KrushiAR',
    version: 'Version 1.0.0',
    logout: 'Logout',
    logoutAlertTitle: 'Logout',
    logoutAlertMsg: 'Are you sure you want to logout from KrushiAR?',
    cancel: 'Cancel',
  },
  mr: {
    // Tabs
    tabHome: 'मुख्यपृष्ठ',
    tabFarm: 'माझे शेत',
    tabScan: 'AR स्कॅन',
    tabMarket: 'बाजार भाव',
    tabProfile: 'प्रोफाइल',

    // Common
    chopdaJalgaon: 'चोपडा, जळगाव',
    chopda: 'चोपडा',
    jalgaon: 'जळगाव',
    seeAll: 'सर्व पहा →',
    addCrop: 'पीक जोडा',
    details: 'तपशील',
    view: 'पहा',
    edit: 'संपादित करा',
    daysLeftText: 'दिवस शिल्लक',
    acre: 'एकर',

    // Dashboard (Home)
    tagline: 'उज्ज्वल भविष्यासाठी स्मार्ट शेती',
    heroTitle: 'शेती स्मार्ट,\nभविष्य उज्ज्वल !',
    heroSub: 'तंत्रज्ञानाच्या मदतीने अधिक उत्पादन,\nकमी खर्च आणि जास्त नफा.',
    partlyCloudy: 'अंशतः ढगाळ',
    rainChance: 'पावसाची शक्यता',
    humidity: 'हवेतील आर्द्रता',
    windSpeed: 'वाऱ्याचा वेग',
    arScanCrops: 'AR पीक\nस्कॅन',
    irrigationGuide: 'सिंचन\nमार्गदर्शक',
    fertilizerRecommend: 'खत\nशिफारस',
    marketPrices: 'बाजार\nभाव',
    todaysTasks: 'आजची शेती कामे',
    task1: 'मातीतील ओलावा तपासा (सोयाबीन)',
    task2: 'पाणी देणे (मका)',
    task3: 'खत देणे (कापूस)',
    task4: 'कीड तपासणी (कांदा)',
    mandiDistrictSub: '(जळगाव बाजार समिती)',
    myCrops: 'माझी पिके',
    arFarmScan: 'AR शेती स्कॅन',
    arFarmScanDesc: 'रोगांचे निदान, वाढीची अवस्था आणि AI सल्ल्यासाठी पिकाचा फोटो घ्या.',
    startScanning: 'स्कॅन सुरू करा →',
    govtSchemes: 'शासकीय योजना',
    govtSchemesSub: 'शेतकऱ्यांसाठी ताज्या सबसिडी आणि योजना',
    agriProducts: 'कृषी उत्पादने',
    agriProductsSub: 'बियाणे, खते, उपकरणे आणि इतर',
    farmAnalytics: 'शेती विश्लेषण',
    farmAnalyticsSub: 'तुमचा खर्च, उत्पादन आणि नफा ट्रॅक करा',
    weatherAdvisory: 'हवामान सल्ला',
    weatherAdvisorySub: 'पिकानिहाय हवामान अंदाज व सूचना',
    promoTitle: 'तुमच्या भाषेत AI पीक सल्ला मिळवा',
    promoDesc: 'पिकातील समस्या ओळखण्यासाठी फोटो काढा किंवा AR वापरा आणि तज्ञांकडून त्वरित उपाय मिळवा.',
    tryNow: 'आता वापरा →',

    // Crops & Stages
    cropSoybean: 'सोयाबीन',
    cropMaize: 'मका',
    cropCotton: 'कापूस',
    cropOnion: 'कांदा',
    cropWheat: 'गहू',
    cropChana: 'हरभरा',
    cropTur: 'तूर (अरहर)',
    stageVegetative: 'शाकीय वाढ अवस्था',
    stageGrowing: 'वाढीची अवस्था',
    stageLandPrep: 'जमीन मशागत',
    stageFlowering: 'फुलोरा अवस्था',

    // My Farm
    screenTitleFarm: 'माझे शेत',
    screenSubFarm: 'तुमची जमीन, पिके आणि शेताचे नियोजन',
    totalFarmArea: 'एकूण शेत क्षेत्र',
    cropsCount: 'माझी पिके (4)',
    soilHealth: 'मातीचे आरोग्य',
    soilHealthSub: 'मातीतील पोषणमूल्ये तपासा आणि सल्ला घ्या',
    irrigation: 'पाणी नियोजन',
    irrigationSub: 'पाणी देण्याची सर्वोत्तम वेळ व प्रमाण',
    fertilizerPlan: 'खत नियोजन',
    fertilizerPlanSub: 'पिकानुसार खत देण्याचे वेळापत्रक',
    filterCrops: 'माझी पिके',
    filterLand: 'शेतजमीन',
    filterTasks: 'कामे',
    filterExpenses: 'खर्च',
    filterAnalytics: 'विश्लेषण',
    sowingDate: 'पेरणी दिनांक',

    // Market
    screenTitleMarket: 'बाजार भाव',
    screenSubMarket: 'पिकांचे ताजे दर, ट्रेंड्स आणि जवळील बाजार समित्या',
    getLivePrices: 'थेट बाजार\nभाव मिळवा',
    getLivePricesSub: 'दरांची तुलना करा, जवळील बाजार शोधा\nआणि तुमच्या पिकाला सर्वोत्तम भाव मिळवा',
    nearbyMandisBtn: 'जवळील बाजार समित्या →',
    filterCropPrices: 'पिकांचे दर',
    filterNearbyMandis: 'जवळील बाजार',
    filterPriceTrends: 'भाव ट्रेंड्स',
    filterTrade: 'खरेदी / विक्री',
    popularCrops: 'लोकप्रिय पिके',
    mandiPricesTitle: 'मंडी भाव',
    tableCrop: 'पीक',
    tableModal: 'सरासरी भाव\n(₹ / क्विंटल)',
    tableMin: 'किमान भाव\n(₹ / क्विंटल)',
    tableMax: 'कमाल भाव\n(₹ / क्विंटल)',
    tableChange: 'बदल\n(आज)',
    tableAction: 'पहा',
    priceTrendTitle: 'भाव चढ-उतार ट्रेंड',
    currentPrice: 'चालू भाव',
    vsLastWeek: 'मागील आठवड्यापेक्षा',
    marketNews: 'बाजार बातम्या',
    marketNewsSub: 'पिकांचे दर आणि बाजारपेठेतील ताज्या घडामोडी',
    sellToBuyers: 'खरेदीदारांना विका',
    sellToBuyersSub: 'स्थानिक व्यापारी आणि खरेदीदारांशी थेट संपर्क',
    priceAlerts: 'भाव सूचना (Alerts)',
    priceAlertsSub: 'तुमचा इच्छित भाव आल्यावर त्वरित सूचना मिळवा',
    exportOpps: 'निर्यात संधी',
    exportOppsSub: 'आंतरराष्ट्रीय मागणी आणि निर्यात भाव तपासा',

    // Profile / Settings
    screenTitle: 'प्रोफाइल',
    screenSub: 'तुमचे खाते आणि शेतीचे तपशील व्यवस्थापित करा',
    editProfile: 'संपादित करा',
    crops: 'पिके',
    acres: 'एकर',
    pendingTasks: 'प्रलंबित कामे',
    farmHealth: 'शेती आरोग्य',
    farmHealthLabel: 'शेती आरोग्य',
    farmHealthVal: 'उत्कृष्ट',
    farmMgmt: 'शेती व्यवस्थापन',
    myFarm: 'माझे शेत',
    myFarmSub: 'तुमची जमीन, पिके आणि शेताचे नियोजन',
    myFarmRecords: 'शेतीचे रेकॉर्ड्स',
    myFarmRecordsSub: 'पिकांचा इतिहास, खर्च आणि उत्पादन',
    myLocations: 'माझी स्थाने',
    myLocationsSub: 'शेताची स्थाने आणि सीमा व्यवस्थापित करा',
    accountSettings: 'खाते सेटिंग्ज',
    personalInfo: 'वैयक्तिक माहिती',
    personalInfoSub: 'तुमचे वैयक्तिक तपशील व्यवस्थापित करा',
    privacySecurity: 'गोपनीयता आणि सुरक्षा',
    privacySecuritySub: 'पासवर्ड बदला, डेटा व्यवस्थापित करा',
    notifications: 'सूचना (Notifications)',
    notificationsSub: 'अ‍ॅपच्या सूचना व्यवस्थापित करा',
    appSupport: 'अ‍ॅप आणि समर्थन',
    language: 'भाषा',
    languageSub: 'तुमची पसंतीची भाषा निवडा',
    appSettings: 'अ‍ॅप सेटिंग्ज',
    appSettingsSub: 'थीम, युनिट्स, ऑफलाइन मोड',
    helpSupport: 'मदत आणि सहाय्य',
    helpSupportSub: 'वारंवार विचारले जाणारे प्रश्न, संपर्क',
    aboutApp: 'कृषीAR बद्दल',
    version: 'आवृत्ती 1.0.0',
    logout: 'लॉग आउट करा',
    logoutAlertTitle: 'लॉग आउट',
    logoutAlertMsg: 'तुम्ही नक्की कृषीAR मधून बाहेर पडू इच्छिता?',
    cancel: 'रद्द करा',
  },
  hi: {
    // Tabs
    tabHome: 'होम',
    tabFarm: 'मेरा खेत',
    tabScan: 'AR स्कैन',
    tabMarket: 'मंडी भाव',
    tabProfile: 'प्रोफाइल',

    // Common
    chopdaJalgaon: 'चोपड़ा, जलगांव',
    chopda: 'चोपड़ा',
    jalgaon: 'जलगांव',
    seeAll: 'सभी देखें →',
    addCrop: 'फसल जोड़ें',
    details: 'विवरण',
    view: 'देखें',
    edit: 'संपादित करें',
    daysLeftText: 'दिन शेष',
    acre: 'एकड़',

    // Dashboard (Home)
    tagline: 'उज्ज्वल भविष्य के लिए स्मार्ट खेती',
    heroTitle: 'खेती स्मार्ट,\nभविष्य उज्ज्वल !',
    heroSub: 'आधुनिक तकनीक की मदद से: अधिक उत्पादन,\nकम लागत और ज्यादा मुनाफा।',
    partlyCloudy: 'आंशिक बादल',
    rainChance: 'बारिश की संभावना',
    humidity: 'नमी (Humidity)',
    windSpeed: 'हवा की गति',
    arScanCrops: 'AR फसल\nस्कैन',
    irrigationGuide: 'सिंचाई\nगाइड',
    fertilizerRecommend: 'उर्वरक\nसिफारिश',
    marketPrices: 'मंडी\nभाव',
    todaysTasks: 'आज के कृषि कार्य',
    task1: 'मिट्टी की नमी जांचें (सोयाबीन)',
    task2: 'सिंचाई करें (मक्का)',
    task3: 'उर्वरक डालें (कपास)',
    task4: 'कीट निरीक्षण (प्याज)',
    mandiDistrictSub: '(जलगांव मंडी भाव)',
    myCrops: 'मेरी फसलें',
    arFarmScan: 'AR खेत स्कैन',
    arFarmScanDesc: 'रोग पहचान, विकास चरण और AI सलाह के लिए अपनी फसल की फोटो लें।',
    startScanning: 'स्कैन शुरू करें →',
    govtSchemes: 'सरकारी योजनाएं',
    govtSchemesSub: 'किसानों के लिए नवीनतम सब्सिडी और योजनाएं',
    agriProducts: 'कृषि उत्पाद',
    agriProductsSub: 'बीज, उर्वरक, उपकरण और बहुत कुछ',
    farmAnalytics: 'कृषि विश्लेषण',
    farmAnalyticsSub: 'अपनी लागत, उपज और लाभ को ट्रैक करें',
    weatherAdvisory: 'मौसम सलाह',
    weatherAdvisorySub: 'फसल विशिष्ट मौसम अलर्ट और पूर्वानुमान',
    promoTitle: 'अपनी भाषा में AI फसल सलाह पाएं',
    promoDesc: 'फसल की समस्याओं को पहचानने के लिए फोटो लें या AR का उपयोग करें और तुरंत समाधान पाएं।',
    tryNow: 'अभी आजमाएं →',

    // Crops & Stages
    cropSoybean: 'सोयाबीन',
    cropMaize: 'मक्का',
    cropCotton: 'कपास',
    cropOnion: 'प्याज',
    cropWheat: 'गेहूं',
    cropChana: 'चना',
    cropTur: 'अरहर (तुअर)',
    stageVegetative: 'वानस्पतिक अवस्था',
    stageGrowing: 'विकास अवस्था',
    stageLandPrep: 'खेत की तैयारी',
    stageFlowering: 'फूल आने की अवस्था',

    // My Farm
    screenTitleFarm: 'मेरा खेत',
    screenSubFarm: 'अपनी जमीन, फसलें और भूखंड प्रबंधित करें',
    totalFarmArea: 'कुल खेत क्षेत्र',
    cropsCount: 'मेरी फसलें (4)',
    soilHealth: 'मृदा स्वास्थ्य',
    soilHealthSub: 'मिट्टी के पोषक तत्वों की जांच करें और सुझाव पाएं',
    irrigation: 'सिंचाई प्रबंधन',
    irrigationSub: 'सर्वोत्तम समय और पानी की मात्रा',
    fertilizerPlan: 'उर्वरक योजना',
    fertilizerPlanSub: 'अनुकूलित उर्वरक अनुसूची प्राप्त करें',
    filterCrops: 'मेरी फसलें',
    filterLand: 'कृषि भूमि',
    filterTasks: 'कार्य',
    filterExpenses: 'खर्च',
    filterAnalytics: 'विश्लेषण',
    sowingDate: 'बुवाई तिथि',

    // Market
    screenTitleMarket: 'मंडी भाव',
    screenSubMarket: 'फसलों के नवीनतम भाव, रुझान और नजदीकी मंडियां',
    getLivePrices: 'लाइव मंडी\nभाव प्राप्त करें',
    getLivePricesSub: 'दरों की तुलना करें, पास की मंडियां खोजें\nऔर अपनी फसलों का सर्वोत्तम मूल्य प्राप्त करें',
    nearbyMandisBtn: 'नजदीकी मंडियां →',
    filterCropPrices: 'फसल भाव',
    filterNearbyMandis: 'पास की मंडियां',
    filterPriceTrends: 'भाव रुझान',
    filterTrade: 'खरीदें / बेचें',
    popularCrops: 'लोकप्रिय फसलें',
    mandiPricesTitle: 'मंडी भाव',
    tableCrop: 'फसल',
    tableModal: 'औसत भाव\n(₹ / क्विंटल)',
    tableMin: 'न्यूनतम भाव\n(₹ / क्विंटल)',
    tableMax: 'अधिकतम भाव\n(₹ / क्विंटल)',
    tableChange: 'बदलाव\n(आज)',
    tableAction: 'देखें',
    priceTrendTitle: 'मूल्य रुझान (Price Trend)',
    currentPrice: 'वर्तमान मूल्य',
    vsLastWeek: 'पिछले सप्ताह की तुलना में',
    marketNews: 'बाजार समाचार',
    marketNewsSub: 'फसल की कीमतों और बाजार के रुझानों पर नवीनतम अपडेट',
    sellToBuyers: 'खरीदारों को बेचें',
    sellToBuyersSub: 'स्थानीय खरीदारों और व्यापारियों से सीधे जुड़ें',
    priceAlerts: 'मूल्य अलर्ट',
    priceAlertsSub: 'लक्ष्य मूल्य तक पहुंचने पर सूचना प्राप्त करें',
    exportOpps: 'निर्यात के अवसर',
    exportOppsSub: 'अंतरराष्ट्रीय मांग और निर्यात कीमतों की जांच करें',

    // Profile / Settings
    screenTitle: 'प्रोफाइल',
    screenSub: 'अपना खाता और खेती का विवरण प्रबंधित करें',
    editProfile: 'संपादित करें',
    crops: 'फसलें',
    acres: 'एकड़',
    pendingTasks: 'लंबित कार्य',
    farmHealth: 'खेत का स्वास्थ्य',
    farmHealthLabel: 'खेत का स्वास्थ्य',
    farmHealthVal: 'उत्तम',
    farmMgmt: 'कृषि प्रबंधन',
    myFarm: 'मेरा खेत',
    myFarmSub: 'अपनी जमीन, फसलें और भूखंड प्रबंधित करें',
    myFarmRecords: 'खेत का रिकॉर्ड',
    myFarmRecordsSub: 'फसल इतिहास, खर्च और उपज देखें',
    myLocations: 'मेरे स्थान',
    myLocationsSub: 'खेत के स्थान और सीमाएं प्रबंधित करें',
    accountSettings: 'खाता सेटिंग्स',
    personalInfo: 'व्यक्तिगत जानकारी',
    personalInfoSub: 'अपने व्यक्तिगत विवरण प्रबंधित करें',
    privacySecurity: 'गोपनीयता और सुरक्षा',
    privacySecuritySub: 'पासवर्ड बदलें, डेटा प्रबंधित करें',
    notifications: 'सूचनाएं (Notifications)',
    notificationsSub: 'ऐप सूचनाएं प्रबंधित करें',
    appSupport: 'ऐप और सहायता',
    language: 'भाषा',
    languageSub: 'अपनी पसंदीदा भाषा चुनें',
    appSettings: 'ऐप सेटिंग्स',
    appSettingsSub: 'थीम, इकाइयां, ऑफ़लाइन मोड',
    helpSupport: 'सहायता और संपर्क',
    helpSupportSub: 'अक्सर पूछे जाने वाले प्रश्न, संपर्क करें',
    aboutApp: 'कृषिAR के बारे में',
    version: 'संस्करण 1.0.0',
    logout: 'लॉग आउट',
    logoutAlertTitle: 'लॉग आउट',
    logoutAlertMsg: 'क्या आप निश्चित रूप से कृषिAR से लॉग आउट करना चाहते हैं?',
    cancel: 'रद्द करें',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations.en;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: translations.en,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');
  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
