import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'mr' | 'hi';

export const translations = {
  en: {
    // Tabs
    tabHome: 'Home',
    tabFarm: 'My Farm',
    tabScan: 'AR Scan',
    tabMarket: 'Market',
    tabProfile: 'Profile',

    // Common
    chopdaJalgaon: 'Chopda, Jalgaon',
    chopda: 'Chopda',
    jalgaon: 'Jalgaon',
    seeAll: 'See All →',
    addCrop: 'Add Crop',
    details: 'Details',
    view: 'View',
    edit: 'Edit',
    daysLeftText: 'days left',
    acre: 'Acre',

    // Dashboard (Home)
    tagline: 'Smart Farming for a Better Tomorrow',
    heroTitle: 'Smart Farming,\nBright Future !',
    heroSub: 'With modern technology: Higher yield,\nlower cost, and higher profits.',
    partlyCloudy: 'Partly Cloudy',
    rainChance: 'Rain Chance',
    humidity: 'Humidity',
    windSpeed: 'Wind Speed',
    arScanCrops: 'AR Scan\nCrops',
    irrigationGuide: 'Irrigation\nGuide',
    fertilizerRecommend: 'Fertilizer\nRecommend',
    marketPrices: 'Market\nPrices',
    todaysTasks: "Today's Farm Tasks",
    task1: 'Check soil moisture (Soybean)',
    task2: 'Irrigation (Maize)',
    task3: 'Apply fertilizer (Cotton)',
    task4: 'Inspect for pests (Onion)',
    mandiDistrictSub: '(Jalgaon Mandi)',
    myCrops: 'My Crops',
    arFarmScan: 'AR Farm Scan',
    arFarmScanDesc: 'Take a photo of your crop to detect disease, growth stage and get AI advice.',
    startScanning: 'Start Scanning →',
    govtSchemes: 'Government Schemes',
    govtSchemesSub: 'Latest subsidies and schemes for farmers',
    agriProducts: 'Agri Products',
    agriProductsSub: 'Seeds, fertilizers, equipment and more',
    farmAnalytics: 'Farm Analytics',
    farmAnalyticsSub: 'Track your farm cost, yield and profit',
    weatherAdvisory: 'Weather Advisory',
    weatherAdvisorySub: 'Get crop specific weather alerts',
    promoTitle: 'Get AI Crop Guidance in Your Language',
    promoDesc: 'Take a photo or use AR to identify crop problems and get instant solution from experts.',
    tryNow: 'Try Now →',

    // Crops & Stages
    cropSoybean: 'Soybean',
    cropMaize: 'Maize',
    cropCotton: 'Cotton',
    cropOnion: 'Onion',
    cropWheat: 'Wheat',
    cropChana: 'Chana',
    cropTur: 'Tur (Arhar)',
    stageVegetative: 'Vegetative Stage',
    stageGrowing: 'Growing Stage',
    stageLandPrep: 'Land Preparation',
    stageFlowering: 'Flowering Stage',

    // My Farm
    screenTitleFarm: 'My Farm',
    screenSubFarm: 'Manage your land, crops and activities',
    totalFarmArea: 'Total Farm Area',
    cropsCount: 'My Crops (4)',
    soilHealth: 'Soil Health',
    soilHealthSub: 'Check soil nutrients and get suggestions',
    irrigation: 'Irrigation',
    irrigationSub: 'Best time & water recommendation',
    fertilizerPlan: 'Fertilizer Plan',
    fertilizerPlanSub: 'Get customized fertilizer schedule',
    filterCrops: 'My Crops',
    filterLand: 'Farm Land',
    filterTasks: 'Tasks',
    filterExpenses: 'Expenses',
    filterAnalytics: 'Analytics',
    sowingDate: 'Sowing Date',

    // Market
    screenTitleMarket: 'Market',
    screenSubMarket: 'Check latest crop prices, trends and nearby mandis',
    getLivePrices: 'Get Live\nMarket Prices',
    getLivePricesSub: 'Compare rates, find nearby mandis\nand get the best price for your crops',
    nearbyMandisBtn: 'Nearby Mandis →',
    filterCropPrices: 'Crop Prices',
    filterNearbyMandis: 'Nearby Mandis',
    filterPriceTrends: 'Price Trends',
    filterTrade: 'Sell / Buy',
    popularCrops: 'Popular Crops',
    mandiPricesTitle: 'Mandi Prices',
    tableCrop: 'Crop',
    tableModal: 'Modal Price\n(₹ / Qtl)',
    tableMin: 'Min Price\n(₹ / Qtl)',
    tableMax: 'Max Price\n(₹ / Qtl)',
    tableChange: 'Change\n(Today)',
    tableAction: 'View',
    priceTrendTitle: 'Price Trend',
    currentPrice: 'Current Price',
    vsLastWeek: 'vs last week',
    marketNews: 'Market News',
    marketNewsSub: 'Latest updates on crop prices and market trends',
    sellToBuyers: 'Sell to Buyers',
    sellToBuyersSub: 'Connect with local buyers and traders',
    priceAlerts: 'Price Alerts',
    priceAlertsSub: 'Get notified when price reaches your target',
    exportOpps: 'Export Opportunities',
    exportOppsSub: 'Check export demand and international prices',

    // Profile / Settings
    screenTitle: 'Profile',
    screenSub: 'Manage your account and farm details',
    editProfile: 'Edit Profile',
    crops: 'Crops',
    acres: 'Acres',
    pendingTasks: 'Pending Tasks',
    farmHealth: 'Farm Health',
    farmHealthLabel: 'Farm Health',
    farmHealthVal: 'Good',
    farmMgmt: 'Farm Management',
    myFarm: 'My Farm',
    myFarmSub: 'Manage your land, crops and plots',
    myFarmRecords: 'My Farm Records',
    myFarmRecordsSub: 'View crop history, expenses and yield',
    myLocations: 'My Locations',
    myLocationsSub: 'Manage farm locations and boundaries',
    accountSettings: 'Account Settings',
    personalInfo: 'Personal Information',
    personalInfoSub: 'Manage your personal details',
    privacySecurity: 'Privacy & Security',
    privacySecuritySub: 'Change password, manage data',
    notifications: 'Notifications',
    notificationsSub: 'Manage app notifications',
    appSupport: 'App & Support',
    language: 'Language',
    languageSub: 'Select your preferred language',
    appSettings: 'App Settings',
    appSettingsSub: 'Theme, units, offline mode',
    helpSupport: 'Help & Support',
    helpSupportSub: 'FAQs, contact us',
    aboutApp: 'About KrushiAR',
    version: 'Version 1.0.0',
    logout: 'Logout',
    logoutAlertTitle: 'Logout',
    logoutAlertMsg: 'Are you sure you want to logout from KrushiAR?',
    cancel: 'Cancel',

    // Personal Information Screen
    updateProfilePhoto: 'Update your profile photo',
    changePhoto: 'Change Photo',
    photoLimit: 'JPG, PNG up to 5MB',
    basicInfo: 'Basic Information',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    emailAddress: 'Email Address',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    otherGender: 'Other',
    locationInfo: 'Location Information',
    state: 'State',
    district: 'District',
    taluka: 'Taluka',
    villageCity: 'Village / City',
    pincode: 'Pincode',
    saveChanges: 'Save Changes',
    reset: 'Reset',
    saveSuccess: 'Personal information updated successfully!',
    resetSuccess: 'Form reset to default values.',

    // Crop Details Screen
    cropDetailsTitle: 'Crop Details',
    cropDetailsSub: 'View and manage your crop information',
    varietyLabel: 'Variety',
    varietyJs335: 'JS 335',
    editCrop: 'Edit Crop',
    plotArea: 'Plot Area',
    plotAreaVal: '1.5 Acres',
    sowingDateLabel: 'Sowing Date',
    sowingDateVal: '01 Jun 2026',
    expectedHarvest: 'Expected Harvest',
    expectedHarvestVal: '25 Sep 2026',
    daysLeft: 'Days Left',
    daysLeftVal: '25 Days',
    growthProgress: 'Growth Progress',
    progress: 'Progress',
    stageVegetativeShort: 'Vegetative',
    stageFloweringShort: 'Flowering',
    stagePodFormation: 'Pod Formation',
    stageMaturity: 'Maturity',
    tabOverview: 'Overview',
    tabActivities: 'Activities',
    tabExpenses: 'Expenses',
    tabYield: 'Yield',
    tabPhotos: 'Photos',
    tabAdvisory: 'Advisory',
    cropHealth: 'Crop Health',
    healthGood: 'Good',
    weatherLabel: 'Weather',
    clearSky: 'Clear Sky',
    soilInformation: 'Soil Information',
    soilPh: 'pH',
    nitrogen: 'Nitrogen (N)',
    phosphorus: 'Phosphorus (P)',
    potassium: 'Potassium (K)',
    levelMedium: 'Medium',
    levelHigh: 'High',
    irrigationSchedule: 'Irrigation Schedule',
    viewAll: 'View All',
    recentPhotos: 'Recent Photos',
    photoHealthyGrowth: 'Healthy growth',
    photoGoodDev: 'Good development',
    photoVegStage: 'Vegetative stage',
    photoUniformGrowth: 'Uniform growth',
    pestDiseaseStatus: 'Pest & Disease Status',
    noMajorIssues: 'No major issues',
    pestDesc: 'Your crop looks healthy. Keep monitoring regularly.',
    expertAdvisory: 'Expert Advisory',
    advisoryDesc: 'Apply second dose of nitrogen fertilizer within next 7 days for better vegetative growth.',

    // Farm Tasks Screen
    farmTasksTitle: 'Farm Tasks',
    farmTasksSub: 'Manage and track all your farming activities',
    allTasks: 'All Tasks',
    pendingTasksTab: 'Pending',
    completedTasksTab: 'Completed',
    todaysTasksSection: "Today's Tasks",
    upcomingTasksSection: 'Upcoming Tasks',
    next7Days: 'Next 7 Days',
    priorityHigh: 'High',
    priorityMedium: 'Medium',
    priorityLow: 'Low',
    addTask: 'Add Task',
    newTaskTitle: 'New Farm Task',
    taskCheckSoilMoisture: 'Check soil moisture',
    taskCheckSoilMoistureSub: 'Soybean • Plot 1 (1.5 Acre)',
    taskIrrigationTitle: 'Irrigation',
    taskIrrigationSub: 'Maize • Plot 2 (2 Acre)',
    taskApplyFertilizer: 'Apply fertilizer (Urea)',
    taskApplyFertilizerSub: 'Cotton • Plot 3 (1 Acre)',
    taskWeeding: 'Weeding',
    taskWeedingSub: 'Onion • Plot 4 (1 Acre)',
    taskPestMonitoring: 'Pest monitoring',
    taskPestMonitoringSub: 'Soybean • Plot 1 (1.5 Acre)',
    taskFoliarSpray: 'Foliar spray',
    taskFoliarSpraySub: 'Maize • Plot 2 (2 Acre)',
    taskHarvestPrep: 'Harvest preparation',
    taskHarvestPrepSub: 'Cotton • Plot 3 (1 Acre)',
    dayMon: 'Mon',
    dayTue: 'Tue',
    dayWed: 'Wed',
    dayThu: 'Thu',
    dayFri: 'Fri',
    daySat: 'Sat',
    daySun: 'Sun',
    monthOct: 'Oct',
    selectLanguageModalTitle: 'Select Language',
    changeLanguageBtn: 'Language',

    // Notifications Screen
    notificationsTitle: 'Notifications',
    notifHeaderSub: 'Stay updated with your farm activities',
    markAllRead: 'Mark all read',
    filterAll: 'All',
    filterTasksCat: 'Tasks',
    filterCropsCat: 'Crops',
    filterWeatherCat: 'Weather',
    filterMarketCat: 'Market',
    filterSystemCat: 'System',
    sectionToday: 'Today',
    sectionYesterday: 'Yesterday',
    sectionThisWeek: 'This Week',
    newNotificationsBadge: 'new',

    // Weather Screen
    weatherTitle: 'Weather',
    weatherScreenSub: 'Get weather updates for your farm',
    hourlyForecast: 'Hourly',
    sevenDaysForecast: '7 Days',
    rainfall: 'Rainfall',
    wind: 'Wind',
    uvIndex: 'UV Index',
    keyWeatherDetails: 'Key Weather Details',
    sevenDayForecastTitle: '7 Day Forecast',
    farmingRecommendations: 'Farming Recommendations',
    viewMore: 'View More',
    viewDetails: 'View Details',
    goodForIrrigation: 'Good for Irrigation',
    irrigationDesc: 'No rainfall expected today. Suitable time for irrigation between 10:00 AM - 4:00 PM.',
    highTempAlert: 'High Temperature Alert',
    highTempDesc: 'Temperature may reach 35°C. Provide adequate water to crops and avoid field work during afternoon.',
    moderateWind: 'Moderate Wind',
    moderateWindDesc: 'Wind speed around 12 km/h from NE direction. Safe for spraying operations.',
  },
  mr: {
    // Tabs
    tabHome: 'मुख्यपृष्ठ',
    tabFarm: 'माझे शेत',
    tabScan: 'AR स्कॅन',
    tabMarket: 'बाजार भाव',
    tabProfile: 'प्रोफाइल',

    // Common
    chopdaJalgaon: 'चोपडा, जळगाव',
    chopda: 'चोपडा',
    jalgaon: 'जळगाव',
    seeAll: 'सर्व पहा →',
    addCrop: 'पीक जोडा',
    details: 'तपशील',
    view: 'पहा',
    edit: 'संपादित करा',
    daysLeftText: 'दिवस शिल्लक',
    acre: 'एकर',

    // Dashboard (Home)
    tagline: 'उज्ज्वल भविष्यासाठी स्मार्ट शेती',
    heroTitle: 'शेती स्मार्ट,\nभविष्य उज्ज्वल !',
    heroSub: 'तंत्रज्ञानाच्या मदतीने अधिक उत्पादन,\nकमी खर्च आणि जास्त नफा.',
    partlyCloudy: 'अंशतः ढगाळ',
    rainChance: 'पावसाची शक्यता',
    humidity: 'हवेतील आर्द्रता',
    windSpeed: 'वाऱ्याचा वेग',
    arScanCrops: 'AR पीक\nस्कॅन',
    irrigationGuide: 'सिंचन\nमार्गदर्शक',
    fertilizerRecommend: 'खत\nशिफारस',
    marketPrices: 'बाजार\nभाव',
    todaysTasks: 'आजची शेती कामे',
    task1: 'मातीतील ओलावा तपासा (सोयाबीन)',
    task2: 'पाणी देणे (मका)',
    task3: 'खत देणे (कापूस)',
    task4: 'कीड तपासणी (कांदा)',
    mandiDistrictSub: '(जळगाव बाजार समिती)',
    myCrops: 'माझी पिके',
    arFarmScan: 'AR शेती स्कॅन',
    arFarmScanDesc: 'रोगांचे निदान, वाढीची अवस्था आणि AI सल्ल्यासाठी पिकाचा फोटो घ्या.',
    startScanning: 'स्कॅन सुरू करा →',
    govtSchemes: 'शासकीय योजना',
    govtSchemesSub: 'शेतकऱ्यांसाठी ताज्या सबसिडी आणि योजना',
    agriProducts: 'कृषी उत्पादने',
    agriProductsSub: 'बियाणे, खते, उपकरणे आणि इतर',
    farmAnalytics: 'शेती विश्लेषण',
    farmAnalyticsSub: 'तुमचा खर्च, उत्पादन आणि नफा ट्रॅक करा',
    weatherAdvisory: 'हवामान सल्ला',
    weatherAdvisorySub: 'पिकानिहाय हवामान अंदाज व सूचना',
    promoTitle: 'तुमच्या भाषेत AI पीक सल्ला मिळवा',
    promoDesc: 'पिकातील समस्या ओळखण्यासाठी फोटो काढा किंवा AR वापरा आणि तज्ञांकडून त्वरित उपाय मिळवा.',
    tryNow: 'आता वापरा →',

    // Crops & Stages
    cropSoybean: 'सोयाबीन',
    cropMaize: 'मका',
    cropCotton: 'कापूस',
    cropOnion: 'कांदा',
    cropWheat: 'गहू',
    cropChana: 'हरभरा',
    cropTur: 'तूर (अरहर)',
    stageVegetative: 'शाकीय वाढ अवस्था',
    stageGrowing: 'वाढीची अवस्था',
    stageLandPrep: 'जमीन मशागत',
    stageFlowering: 'फुलोरा अवस्था',

    // My Farm
    screenTitleFarm: 'माझे शेत',
    screenSubFarm: 'तुमची जमीन, पिके आणि शेताचे नियोजन',
    totalFarmArea: 'एकूण शेत क्षेत्र',
    cropsCount: 'माझी पिके (4)',
    soilHealth: 'मातीचे आरोग्य',
    soilHealthSub: 'मातीतील पोषणमूल्ये तपासा आणि सल्ला घ्या',
    irrigation: 'पाणी नियोजन',
    irrigationSub: 'पाणी देण्याची सर्वोत्तम वेळ व प्रमाण',
    fertilizerPlan: 'खत नियोजन',
    fertilizerPlanSub: 'पिकानुसार खत देण्याचे वेळापत्रक',
    filterCrops: 'माझी पिके',
    filterLand: 'शेतजमीन',
    filterTasks: 'कामे',
    filterExpenses: 'खर्च',
    filterAnalytics: 'विश्लेषण',
    sowingDate: 'पेरणी दिनांक',

    // Market
    screenTitleMarket: 'बाजार भाव',
    screenSubMarket: 'पिकांचे ताजे दर, ट्रेंड्स आणि जवळील बाजार समित्या',
    getLivePrices: 'थेट बाजार\nभाव मिळवा',
    getLivePricesSub: 'दरांची तुलना करा, जवळील बाजार शोधा\nआणि तुमच्या पिकाला सर्वोत्तम भाव मिळवा',
    nearbyMandisBtn: 'जवळील बाजार समित्या →',
    filterCropPrices: 'पिकांचे दर',
    filterNearbyMandis: 'जवळील बाजार',
    filterPriceTrends: 'भाव ट्रेंड्स',
    filterTrade: 'खरेदी / विक्री',
    popularCrops: 'लोकप्रिय पिके',
    mandiPricesTitle: 'मंडी भाव',
    tableCrop: 'पीक',
    tableModal: 'सरासरी भाव\n(₹ / क्विंटल)',
    tableMin: 'किमान भाव\n(₹ / क्विंटल)',
    tableMax: 'कमाल भाव\n(₹ / क्विंटल)',
    tableChange: 'बदल\n(आज)',
    tableAction: 'पहा',
    priceTrendTitle: 'भाव चढ-उतार ट्रेंड',
    currentPrice: 'चालू भाव',
    vsLastWeek: 'मागील आठवड्यापेक्षा',
    marketNews: 'बाजार बातम्या',
    marketNewsSub: 'पिकांचे दर आणि बाजारपेठेतील ताज्या घडामोडी',
    sellToBuyers: 'खरेदीदारांना विका',
    sellToBuyersSub: 'स्थानिक व्यापारी आणि खरेदीदारांशी थेट संपर्क',
    priceAlerts: 'भाव सूचना (Alerts)',
    priceAlertsSub: 'तुमचा इच्छित भाव आल्यावर त्वरित सूचना मिळवा',
    exportOpps: 'निर्यात संधी',
    exportOppsSub: 'आंतरराष्ट्रीय मागणी आणि निर्यात भाव तपासा',

    // Profile / Settings
    screenTitle: 'प्रोफाइल',
    screenSub: 'तुमचे खाते आणि शेतीचे तपशील व्यवस्थापित करा',
    editProfile: 'संपादित करा',
    crops: 'पिके',
    acres: 'एकर',
    pendingTasks: 'प्रलंबित कामे',
    farmHealth: 'शेती आरोग्य',
    farmHealthLabel: 'शेती आरोग्य',
    farmHealthVal: 'उत्कृष्ट',
    farmMgmt: 'शेती व्यवस्थापन',
    myFarm: 'माझे शेत',
    myFarmSub: 'तुमची जमीन, पिके आणि शेताचे नियोजन',
    myFarmRecords: 'शेतीचे रेकॉर्ड्स',
    myFarmRecordsSub: 'पिकांचा इतिहास, खर्च आणि उत्पादन',
    myLocations: 'माझी स्थाने',
    myLocationsSub: 'शेताची स्थाने आणि सीमा व्यवस्थापित करा',
    accountSettings: 'खाते सेटिंग्ज',
    personalInfo: 'वैयक्तिक माहिती',
    personalInfoSub: 'तुमचे वैयक्तिक तपशील व्यवस्थापित करा',
    privacySecurity: 'गोपनीयता आणि सुरक्षा',
    privacySecuritySub: 'पासवर्ड बदला, डेटा व्यवस्थापित करा',
    notifications: 'सूचना (Notifications)',
    notificationsSub: 'अ‍ॅपच्या सूचना व्यवस्थापित करा',
    appSupport: 'अ‍ॅप आणि समर्थन',
    language: 'भाषा',
    languageSub: 'तुमची पसंतीची भाषा निवडा',
    appSettings: 'अ‍ॅप सेटिंग्ज',
    appSettingsSub: 'थीम, युनिट्स, ऑफलाइन मोड',
    helpSupport: 'मदत आणि सहाय्य',
    helpSupportSub: 'वारंवार विचारले जाणारे प्रश्न, संपर्क',
    aboutApp: 'कृषीAR बद्दल',
    version: 'आवृत्ती 1.0.0',
    logout: 'लॉग आउट करा',
    logoutAlertTitle: 'लॉग आउट',
    logoutAlertMsg: 'तुम्ही नक्की कृषीAR मधून बाहेर पडू इच्छिता?',
    cancel: 'रद्द करा',

    // Personal Information Screen
    updateProfilePhoto: 'तुमचा प्रोफाईल फोटो बदला',
    changePhoto: 'फोटो बदला',
    photoLimit: 'JPG, PNG कमाल 5MB',
    basicInfo: 'मूलभूत माहिती',
    fullName: 'पूर्ण नाव',
    phoneNumber: 'फोन नंबर',
    emailAddress: 'ईमेल पत्ता',
    dateOfBirth: 'जन्मतारीख',
    gender: 'लिंग',
    male: 'पुरुष',
    female: 'स्त्री',
    otherGender: 'इतर',
    locationInfo: 'स्थान माहिती',
    state: 'राज्य',
    district: 'जिल्हा',
    taluka: 'तालुका',
    villageCity: 'गाव / शहर',
    pincode: 'पिनकोड',
    saveChanges: 'बदल जतन करा',
    reset: 'रीसेट करा',
    saveSuccess: 'वैयक्तिक माहिती यशस्वीरित्या जतन केली!',
    resetSuccess: 'माहिती मूळ स्वरूपात रीसेट झाली.',

    // Crop Details Screen
    cropDetailsTitle: 'पिकाचा तपशील',
    cropDetailsSub: 'तुमच्या पिकाची माहिती पहा आणि व्यवस्थापित करा',
    varietyLabel: 'वाण',
    varietyJs335: 'JS ३३५',
    editCrop: 'पीक संपादित करा',
    plotArea: 'प्लॉट क्षेत्र',
    plotAreaVal: '१.५ एकर',
    sowingDateLabel: 'पेरणी दिनांक',
    sowingDateVal: '०१ जून २०२६',
    expectedHarvest: 'अपेक्षित कापणी',
    expectedHarvestVal: '२५ सप्टें २०२६',
    daysLeft: 'दिवस शिल्लक',
    daysLeftVal: '२५ दिवस',
    growthProgress: 'पिकाची वाढ प्रगती',
    progress: 'प्रगती',
    stageVegetativeShort: 'शाकीय वाढ',
    stageFloweringShort: 'फुलोरा',
    stagePodFormation: 'शेंगा भरणे',
    stageMaturity: 'पक्वता',
    tabOverview: 'आढावा',
    tabActivities: 'कामे',
    tabExpenses: 'खर्च',
    tabYield: 'उत्पादन',
    tabPhotos: 'फोटो',
    tabAdvisory: 'सल्ला',
    cropHealth: 'पिकाचे आरोग्य',
    healthGood: 'उत्तम',
    weatherLabel: 'हवामान',
    clearSky: 'निरभ्र आकाश',
    soilInformation: 'मातीची माहिती',
    soilPh: 'सामू (pH)',
    nitrogen: 'नत्र (N)',
    phosphorus: 'स्फुरद (P)',
    potassium: 'पालाश (K)',
    levelMedium: 'मध्यम',
    levelHigh: 'जास्त',
    irrigationSchedule: 'पाणी देण्याचे वेळापत्रक',
    viewAll: 'सर्व पहा',
    recentPhotos: 'नुकतेच काढलेले फोटो',
    photoHealthyGrowth: 'उत्तम वाढ',
    photoGoodDev: 'चांगला विकास',
    photoVegStage: 'शाकीय अवस्था',
    photoUniformGrowth: 'एकसमान वाढ',
    pestDiseaseStatus: 'कीड व रोग स्थिती',
    noMajorIssues: 'कोणतीही समस्या नाही',
    pestDesc: 'तुमचे पीक निरोगी दिसत आहे. नियमित निरीक्षण सुरू ठेवा.',
    expertAdvisory: 'तज्ज्ञ सल्ला',
    advisoryDesc: 'चांगल्या शाकीय वाढीसाठी पुढील ७ दिवसांत नत्र खताचा दुसरा हप्ता द्या.',

    // Farm Tasks Screen
    farmTasksTitle: 'शेतीची कामे',
    farmTasksSub: 'तुमच्या सर्व शेती कामांचे व्यवस्थापन आणि मागोवा घ्या',
    allTasks: 'सर्व कामे',
    pendingTasksTab: 'प्रलंबित',
    completedTasksTab: 'पूर्ण झालेली',
    todaysTasksSection: 'आजची कामे',
    upcomingTasksSection: 'पुढील कामे',
    next7Days: 'पुढील ७ दिवस',
    priorityHigh: 'उच्च',
    priorityMedium: 'मध्यम',
    priorityLow: 'कमी',
    addTask: 'काम जोडा',
    newTaskTitle: 'नवीन शेती काम',
    taskCheckSoilMoisture: 'मातीतील ओलावा तपासा',
    taskCheckSoilMoistureSub: 'सोयाबीन • प्लॉट १ (१.५ एकर)',
    taskIrrigationTitle: 'पाणी देणे',
    taskIrrigationSub: 'मका • प्लॉट २ (२ एकर)',
    taskApplyFertilizer: 'खत देणे (युरिया)',
    taskApplyFertilizerSub: 'कापूस • प्लॉट ३ (१ एकर)',
    taskWeeding: 'खुरपणी (तण काढणे)',
    taskWeedingSub: 'कांदा • प्लॉट ४ (१ एकर)',
    taskPestMonitoring: 'कीड निरीक्षण',
    taskPestMonitoringSub: 'सोयाबीन • प्लॉट १ (१.५ एकर)',
    taskFoliarSpray: 'पानांवर फवारणी',
    taskFoliarSpraySub: 'मका • प्लॉट २ (२ एकर)',
    taskHarvestPrep: 'कापणीची पूर्वतयारी',
    taskHarvestPrepSub: 'कापूस • प्लॉट ३ (१ एकर)',
    dayMon: 'सोम',
    dayTue: 'मंगळ',
    dayWed: 'बुध',
    dayThu: 'गुरु',
    dayFri: 'शुक्र',
    daySat: 'शनि',
    daySun: 'रवि',
    monthOct: 'ऑक्टो',
    selectLanguageModalTitle: 'भाषा निवडा',
    changeLanguageBtn: 'भाषा',

    // Notifications Screen
    notificationsTitle: 'सूचना (Notifications)',
    notifHeaderSub: 'तुमच्या शेतातील घडामोडींची माहिती मिळवा',
    markAllRead: 'सर्व वाचले म्हणून नोंदवा',
    filterAll: 'सर्व',
    filterTasksCat: 'कामे',
    filterCropsCat: 'पिके',
    filterWeatherCat: 'हवामान',
    filterMarketCat: 'बाजार',
    filterSystemCat: 'सिस्टम',
    sectionToday: 'आज',
    sectionYesterday: 'काल',
    sectionThisWeek: 'या आठवड्यात',
    newNotificationsBadge: 'नवीन',

    // Weather Screen
    weatherTitle: 'हवामान',
    weatherScreenSub: 'तुमच्या शेतासाठी हवामानाचे ताजे अंदाज मिळवा',
    hourlyForecast: 'तासनिहाय',
    sevenDaysForecast: '७ दिवस',
    rainfall: 'पाऊस',
    wind: 'वारा',
    uvIndex: 'UV निर्देशांक',
    keyWeatherDetails: 'प्रमुख हवामान तपशील',
    sevenDayForecastTitle: '७ दिवसांचा हवामान अंदाज',
    farmingRecommendations: 'शेतीविषयक शिफारसी',
    viewMore: 'अधिक पहा',
    viewDetails: 'तपशील पहा',
    goodForIrrigation: 'पाणी देण्यासाठी उत्तम',
    irrigationDesc: 'आज पावसाची शक्यता नाही. सकाळी १०:०० ते दुपारी ४:०० दरम्यान पाणी देण्यासाठी योग्य वेळ.',
    highTempAlert: 'उच्च तापमान इशारा',
    highTempDesc: 'तापमान ३५°C पर्यंत पोहोचू शकते. पिकांना पुरेसे पाणी द्या आणि दुपारच्या वेळी शेतात काम करणे टाळा.',
    moderateWind: 'मध्यम वारा',
    moderateWindDesc: 'ईशान्य दिशेकडून वाऱ्याचा वेग सुमारे १२ किमी/तास. फवारणीसाठी सुरक्षित.',
  },
  hi: {
    // Tabs
    tabHome: 'होम',
    tabFarm: 'मेरा खेत',
    tabScan: 'AR स्कैन',
    tabMarket: 'मंडी भाव',
    tabProfile: 'प्रोफाइल',

    // Common
    chopdaJalgaon: 'चोपड़ा, जलगांव',
    chopda: 'चोपड़ा',
    jalgaon: 'जलगांव',
    seeAll: 'सभी देखें →',
    addCrop: 'फसल जोड़ें',
    details: 'विवरण',
    view: 'देखें',
    edit: 'संपादित करें',
    daysLeftText: 'दिन शेष',
    acre: 'एकड़',

    // Dashboard (Home)
    tagline: 'उज्ज्वल भविष्य के लिए स्मार्ट खेती',
    heroTitle: 'खेती स्मार्ट,\nभविष्य उज्ज्वल !',
    heroSub: 'आधुनिक तकनीक की मदद से: अधिक उत्पादन,\nकम लागत और ज्यादा मुनाफा।',
    partlyCloudy: 'आंशिक बादल',
    rainChance: 'बारिश की संभावना',
    humidity: 'नमी (Humidity)',
    windSpeed: 'हवा की गति',
    arScanCrops: 'AR फसल\nस्कैन',
    irrigationGuide: 'सिंचाई\nगाइड',
    fertilizerRecommend: 'उर्वरक\nसिफारिश',
    marketPrices: 'मंडी\nभाव',
    todaysTasks: 'आज के कृषि कार्य',
    task1: 'मिट्टी की नमी जांचें (सोयाबीन)',
    task2: 'सिंचाई करें (मक्का)',
    task3: 'उर्वरक डालें (कपास)',
    task4: 'कीट निरीक्षण (प्याज)',
    mandiDistrictSub: '(जलगांव मंडी भाव)',
    myCrops: 'मेरी फसलें',
    arFarmScan: 'AR खेत स्कैन',
    arFarmScanDesc: 'रोग पहचान, विकास चरण और AI सलाह के लिए अपनी फसल की फोटो लें।',
    startScanning: 'स्कैन शुरू करें →',
    govtSchemes: 'सरकारी योजनाएं',
    govtSchemesSub: 'किसानों के लिए नवीनतम सब्सिडी और योजनाएं',
    agriProducts: 'कृषि उत्पाद',
    agriProductsSub: 'बीज, उर्वरक, उपकरण और बहुत कुछ',
    farmAnalytics: 'कृषि विश्लेषण',
    farmAnalyticsSub: 'अपनी लागत, उपज और लाभ को ट्रैक करें',
    weatherAdvisory: 'मौसम सलाह',
    weatherAdvisorySub: 'फसल विशिष्ट मौसम अलर्ट और पूर्वानुमान',
    promoTitle: 'अपनी भाषा में AI फसल सलाह पाएं',
    promoDesc: 'फसल की समस्याओं को पहचानने के लिए फोटो लें या AR का उपयोग करें और तुरंत समाधान पाएं।',
    tryNow: 'अभी आजमाएं →',

    // Crops & Stages
    cropSoybean: 'सोयाबीन',
    cropMaize: 'मक्का',
    cropCotton: 'कपास',
    cropOnion: 'प्याज',
    cropWheat: 'गेहूं',
    cropChana: 'चना',
    cropTur: 'अरहर (तुअर)',
    stageVegetative: 'वानस्पतिक अवस्था',
    stageGrowing: 'विकास अवस्था',
    stageLandPrep: 'खेत की तैयारी',
    stageFlowering: 'फूल आने की अवस्था',

    // My Farm
    screenTitleFarm: 'मेरा खेत',
    screenSubFarm: 'अपनी जमीन, फसलें और भूखंड प्रबंधित करें',
    totalFarmArea: 'कुल खेत क्षेत्र',
    cropsCount: 'मेरी फसलें (4)',
    soilHealth: 'मृदा स्वास्थ्य',
    soilHealthSub: 'मिट्टी के पोषक तत्वों की जांच करें और सुझाव पाएं',
    irrigation: 'सिंचाई प्रबंधन',
    irrigationSub: 'सर्वोत्तम समय और पानी की मात्रा',
    fertilizerPlan: 'उर्वरक योजना',
    fertilizerPlanSub: 'अनुकूलित उर्वरक अनुसूची प्राप्त करें',
    filterCrops: 'मेरी फसलें',
    filterLand: 'कृषि भूमि',
    filterTasks: 'कार्य',
    filterExpenses: 'खर्च',
    filterAnalytics: 'विश्लेषण',
    sowingDate: 'बुवाई तिथि',

    // Market
    screenTitleMarket: 'मंडी भाव',
    screenSubMarket: 'फसलों के नवीनतम भाव, रुझान और नजदीकी मंडियां',
    getLivePrices: 'लाइव मंडी\nभाव प्राप्त करें',
    getLivePricesSub: 'दरों की तुलना करें, पास की मंडियां खोजें\nऔर अपनी फसलों का सर्वोत्तम मूल्य प्राप्त करें',
    nearbyMandisBtn: 'नजदीकी मंडियां →',
    filterCropPrices: 'फसल भाव',
    filterNearbyMandis: 'पास की मंडियां',
    filterPriceTrends: 'भाव रुझान',
    filterTrade: 'खरीदें / बेचें',
    popularCrops: 'लोकप्रिय फसलें',
    mandiPricesTitle: 'मंडी भाव',
    tableCrop: 'फसल',
    tableModal: 'औसत भाव\n(₹ / क्विंटल)',
    tableMin: 'न्यूनतम भाव\n(₹ / क्विंटल)',
    tableMax: 'अधिकतम भाव\n(₹ / क्विंटल)',
    tableChange: 'बदलाव\n(आज)',
    tableAction: 'देखें',
    priceTrendTitle: 'मूल्य रुझान (Price Trend)',
    currentPrice: 'वर्तमान मूल्य',
    vsLastWeek: 'पिछले सप्ताह की तुलना में',
    marketNews: 'बाजार समाचार',
    marketNewsSub: 'फसल की कीमतों और बाजार के रुझानों पर नवीनतम अपडेट',
    sellToBuyers: 'खरीदारों को बेचें',
    sellToBuyersSub: 'स्थानीय खरीदारों और व्यापारियों से सीधे जुड़ें',
    priceAlerts: 'मूल्य अलर्ट',
    priceAlertsSub: 'लक्ष्य मूल्य तक पहुंचने पर सूचना प्राप्त करें',
    exportOpps: 'निर्यात के अवसर',
    exportOppsSub: 'अंतरराष्ट्रीय मांग और निर्यात कीमतों की जांच करें',

    // Profile / Settings
    screenTitle: 'प्रोफाइल',
    screenSub: 'अपना खाता और खेती का विवरण प्रबंधित करें',
    editProfile: 'संपादित करें',
    crops: 'फसलें',
    acres: 'एकड़',
    pendingTasks: 'लंबित कार्य',
    farmHealth: 'खेत का स्वास्थ्य',
    farmHealthLabel: 'खेत का स्वास्थ्य',
    farmHealthVal: 'उत्तम',
    farmMgmt: 'कृषि प्रबंधन',
    myFarm: 'मेरा खेत',
    myFarmSub: 'अपनी जमीन, फसलें और भूखंड प्रबंधित करें',
    myFarmRecords: 'खेत का रिकॉर्ड',
    myFarmRecordsSub: 'फसल इतिहास, खर्च और उपज देखें',
    myLocations: 'मेरे स्थान',
    myLocationsSub: 'खेत के स्थान और सीमाएं प्रबंधित करें',
    accountSettings: 'खाता सेटिंग्स',
    personalInfo: 'व्यक्तिगत जानकारी',
    personalInfoSub: 'अपने व्यक्तिगत विवरण प्रबंधित करें',
    privacySecurity: 'गोपनीयता और सुरक्षा',
    privacySecuritySub: 'पासवर्ड बदलें, डेटा प्रबंधित करें',
    notifications: 'सूचनाएं (Notifications)',
    notificationsSub: 'ऐप सूचनाएं प्रबंधित करें',
    appSupport: 'ऐप और सहायता',
    language: 'भाषा',
    languageSub: 'अपनी पसंदीदा भाषा चुनें',
    appSettings: 'ऐप सेटिंग्स',
    appSettingsSub: 'थीम, इकाइयां, ऑफ़लाइन मोड',
    helpSupport: 'सहायता और संपर्क',
    helpSupportSub: 'अक्सर पूछे जाने वाले प्रश्न, संपर्क करें',
    aboutApp: 'कृषिAR के बारे में',
    version: 'संस्करण 1.0.0',
    logout: 'लॉग आउट',
    logoutAlertTitle: 'लॉग आउट',
    logoutAlertMsg: 'क्या आप निश्चित रूप से कृषिAR से लॉग आउट करना चाहते हैं?',
    cancel: 'रद्द करें',

    // Personal Information Screen
    updateProfilePhoto: 'अपना प्रोफ़ाइल फ़ोटो अपडेट करें',
    changePhoto: 'फोटो बदलें',
    photoLimit: 'JPG, PNG अधिकतम 5MB',
    basicInfo: 'बुनियादी जानकारी',
    fullName: 'पूरा नाम',
    phoneNumber: 'फ़ोन नंबर',
    emailAddress: 'ईमेल पता',
    dateOfBirth: 'जन्म तिथि',
    gender: 'लिंग',
    male: 'पुरुष',
    female: 'महिला',
    otherGender: 'अन्य',
    locationInfo: 'स्थान की जानकारी',
    state: 'राज्य',
    district: 'ज़िला',
    taluka: 'तहसील',
    villageCity: 'गांव / शहर',
    pincode: 'पिनकोड',
    saveChanges: 'बदलाव सहेजें',
    reset: 'रीसेट करें',
    saveSuccess: 'व्यक्तिगत जानकारी सफलतापूर्वक अपडेट की गई!',
    resetSuccess: 'विवरण रीसेट कर दिया गया है।',

    // Crop Details Screen
    cropDetailsTitle: 'फसल विवरण',
    cropDetailsSub: 'अपनी फसल की जानकारी देखें और प्रबंधित करें',
    varietyLabel: 'किस्म',
    varietyJs335: 'JS 335',
    editCrop: 'फसल संपादित करें',
    plotArea: 'प्लाट क्षेत्र',
    plotAreaVal: '1.5 एकड़',
    sowingDateLabel: 'बुवाई तिथि',
    sowingDateVal: '01 जून 2026',
    expectedHarvest: 'अपेक्षित कटाई',
    expectedHarvestVal: '25 सित 2026',
    daysLeft: 'दिन शेष',
    daysLeftVal: '25 दिन',
    growthProgress: 'फसल वृद्धि प्रगति',
    progress: 'प्रगति',
    stageVegetativeShort: 'वानस्पतिक',
    stageFloweringShort: 'फूल आना',
    stagePodFormation: 'फली विकास',
    stageMaturity: 'परिपक्वता',
    tabOverview: 'अवलोकन',
    tabActivities: 'गतिविधियां',
    tabExpenses: 'खर्च',
    tabYield: 'उपज',
    tabPhotos: 'तस्वीरें',
    tabAdvisory: 'सलाह',
    cropHealth: 'फसल स्वास्थ्य',
    healthGood: 'उत्तम',
    weatherLabel: 'मौसम',
    clearSky: 'साफ आसमान',
    soilInformation: 'मृदा जानकारी',
    soilPh: 'सामू (pH)',
    nitrogen: 'नाइट्रोजन (N)',
    phosphorus: 'फास्फोरस (P)',
    potassium: 'पोटाश (K)',
    levelMedium: 'मध्यम',
    levelHigh: 'उच्च',
    irrigationSchedule: 'सिंचाई अनुसूची',
    viewAll: 'सभी देखें',
    recentPhotos: 'हाल की तस्वीरें',
    photoHealthyGrowth: 'स्वस्थ वृद्धि',
    photoGoodDev: 'अच्छा विकास',
    photoVegStage: 'वानस्पतिक अवस्था',
    photoUniformGrowth: 'समान वृद्धि',
    pestDiseaseStatus: 'कीट एवं रोग स्थिति',
    noMajorIssues: 'कोई बड़ी समस्या नहीं',
    pestDesc: 'आपकी फसल स्वस्थ दिख रही है। नियमित निगरानी जारी रखें।',
    expertAdvisory: 'विशेषज्ञ सलाह',
    advisoryDesc: 'बेहतर वानस्पतिक विकास के लिए अगले 7 दिनों में नाइट्रोजन उर्वरक की दूसरी खुराक दें।',

    // Farm Tasks Screen
    farmTasksTitle: 'कृषि कार्य',
    farmTasksSub: 'अपनी सभी कृषि गतिविधियों को प्रबंधित और ट्रैक करें',
    allTasks: 'सभी कार्य',
    pendingTasksTab: 'लंबित',
    completedTasksTab: 'पूर्ण',
    todaysTasksSection: 'आज के कार्य',
    upcomingTasksSection: 'आगामी कार्य',
    next7Days: 'अगले 7 दिन',
    priorityHigh: 'उच्च',
    priorityMedium: 'मध्यम',
    priorityLow: 'कम',
    addTask: 'कार्य जोड़ें',
    newTaskTitle: 'नया कृषि कार्य',
    taskCheckSoilMoisture: 'मिट्टी की नमी जांचें',
    taskCheckSoilMoistureSub: 'सोयाबीन • प्लाट 1 (1.5 एकड़)',
    taskIrrigationTitle: 'सिंचाई करना',
    taskIrrigationSub: 'मक्का • प्लाट 2 (2 एकड़)',
    taskApplyFertilizer: 'उर्वरक डालें (यूरिया)',
    taskApplyFertilizerSub: 'कपास • प्लाट 3 (1 एकड़)',
    taskWeeding: 'निराई-गुड़ाई (खरपतवार)',
    taskWeedingSub: 'प्याज • प्लाट 4 (1 एकड़)',
    taskPestMonitoring: 'कीट निगरानी',
    taskPestMonitoringSub: 'सोयाबीन • प्लाट 1 (1.5 एकड़)',
    taskFoliarSpray: 'पर्ण छिड़काव',
    taskFoliarSpraySub: 'मक्का • प्लाट 2 (2 एकड़)',
    taskHarvestPrep: 'कटाई की तैयारी',
    taskHarvestPrepSub: 'कपास • प्लाट 3 (1 एकड़)',
    dayMon: 'सोम',
    dayTue: 'मंगल',
    dayWed: 'बुध',
    dayThu: 'गुरु',
    dayFri: 'शुक्र',
    daySat: 'शनि',
    daySun: 'रवि',
    monthOct: 'अक्टू',
    selectLanguageModalTitle: 'भाषा चुनें',
    changeLanguageBtn: 'भाषा',

    // Notifications Screen
    notificationsTitle: 'सूचनाएं (Notifications)',
    notifHeaderSub: 'अपनी कृषि गतिविधियों से अपडेट रहें',
    markAllRead: 'सभी को पढ़ा हुआ चिह्नित करें',
    filterAll: 'सभी',
    filterTasksCat: 'कार्य',
    filterCropsCat: 'फसलें',
    filterWeatherCat: 'मौसम',
    filterMarketCat: 'मंडी',
    filterSystemCat: 'सिस्टम',
    sectionToday: 'आज',
    sectionYesterday: 'कल',
    sectionThisWeek: 'इस सप्ताह',
    newNotificationsBadge: 'नई',

    // Weather Screen
    weatherTitle: 'मौसम',
    weatherScreenSub: 'अपने खेत के लिए मौसम के अपडेट प्राप्त करें',
    hourlyForecast: 'प्रति घंटा',
    sevenDaysForecast: '7 दिन',
    rainfall: 'वर्षा',
    wind: 'हवा',
    uvIndex: 'यूवी इंडेक्स',
    keyWeatherDetails: 'मुख्य मौसम विवरण',
    sevenDayForecastTitle: '7 दिनों का मौसम पूर्वानुमान',
    farmingRecommendations: 'कृषि सिफारिशें',
    viewMore: 'और देखें',
    viewDetails: 'विवरण देखें',
    goodForIrrigation: 'सिंचाई के लिए उपयुक्त',
    irrigationDesc: 'आज बारिश की संभावना नहीं है। सुबह 10:00 से शाम 4:00 के बीच सिंचाई के लिए उपयुक्त समय।',
    highTempAlert: 'उच्च तापमान चेतावनी',
    highTempDesc: 'तापमान 35°C तक पहुंच सकता है। फसलों को पर्याप्त पानी दें और दोपहर में खेत में काम करने से बचें।',
    moderateWind: 'मध्यम हवा',
    moderateWindDesc: 'उत्तर-पूर्व दिशा से हवा की गति लगभग 12 किमी/घंटा। छिड़काव कार्यों के लिए सुरक्षित।',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations.en;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: translations.en,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');
  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
